Pre_capstone_project
Kal2403/capstone-project pull request #1
Opened 2023-05-24 01:28 UTC by Kal2403

1. Added HTML and CSS home-page
2. Added HTML and CSS about-page
3. Added JS menu and section features
4. Added Linters HTML, CSS and Js
5. Added Readme

2023-05-24 03:05 UTC, Shedrack-Sunday requested changes
Hello @Kal2403      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice UI design 👍 

  
# Required Changes  🌵 

- [x] You made some impressive implementations which I must say is a job well done. However, there are a few  features you missed or need to adjust

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-24 03:05 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] Kindly take this section of your README out, as its meant to serve as a guide, but should not be commited to your code base.
- Guided comments like this when added does not makes your work professional, and paying attention too such will enhance your attention to details going forward ✔️

2023-05-24 03:05 UTC, Shedrack-Sunday commented on README.md
> +I would like to thank Microverse for the opportunity
- [ ] The original deign of this work was not initiated by you, there by lets give credit to the main creator of the design.
- As instructed in your project requirements, kindly add in your "Acknowledgements" section an appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). 

## Instructions:
![image](https://github.com/Kal2403/capstone-project/assets/50990925/78c670f2-cad7-400e-9c3e-ec6b12b362f1)

2023-05-24 03:05 UTC, Shedrack-Sunday commented on script.js
> +
- [ ] Instead of using a for loop here, kindly use a function instead. The `map` keyword can also be included in your function to iterate through each pf your `dataSpeakers` array.
- Using the `map` function can provide a more concise and expressive way to achieve the same result as the provided for loop. Here's an example of how you could rewrite the code using the map function:

```
dataSpeakers.map(dataSpeak => {
  const speakCard = document.createElement('div');
  speakCard.classList.add('speakCard');
  speakContainer.appendChild(speakCard);

  const imgCard = document.createElement('img');
  imgCard.classList.add('imgCard');
  imgCard.src = dataSpeak.img;
  speakCard.appendChild(imgCard);

  const descriptionCard = document.createElement('div');
  descriptionCard.classList.add('descriptionCard');
  speakCard.appendChild(descriptionCard);
});
```

2023-05-24 03:05 UTC, Shedrack-Sunday commented on index.html
> +      <p class="hello">"Hello! Sharing world"</p>
- [ ] For semantic purposes, this should be a `hx` not a `p` tag. This follows best practice for proper use of Html tags in your code 👍

2023-05-24 03:05 UTC, Shedrack-Sunday commented on index.html
> +      <h2 class="creative">KAL TECH THINK UNLIMITED 2023</h2>
- [ ] Including at least one `h1` tag in an HTML file improves accessibility, SEO, and document structure by providing a clear main heading. It establishes a logical hierarchy for content and aids in visual styling. Following this best practice enhances user experience and maintains coding consistency.

2023-05-24 03:05 UTC, Shedrack-Sunday commented on index.html
> +      <a class="logo-link" href="index.html"><img class="logo-img" src="img/logo.png"><a/>
- [ ] Kindly provide an `alt` attribute for all your images to professionally fix your code base 👍

2023-05-24 03:05 UTC, Shedrack-Sunday commented on index.html
> +        <a href="index.html"><img src="img/logo2.png"></a>
-  [ ] Kindly add and `alt` attribute here 👍 . This is essential for best practices

2023-05-24 03:05 UTC, Shedrack-Sunday commented on about.html
> +        <a class="desktop-img" href="index.html"><img src="img/Kaltech.png"></a>
- [ ] I suggest you add an `alt` attribute to all sections where you have an image. This follows the best practices for proper image placing on your html code base 👍

2023-05-24 03:05 UTC, Shedrack-Sunday commented on about.html
> +        <img src="img/about2.png">
- [ ] Kindly add an alt attribute to all sections where you have an image. This follows the best practices for proper image placing on your html code base

2023-05-24 03:05 UTC, Shedrack-Sunday commented on about.html
> +      <img src="img/logo2.png">
- [ ] Please add an `alt` attribute to all sections where you have an image. This follows the best practices for proper image placing on your html code base

2023-05-24 03:05 UTC, Shedrack-Sunday commented on about.html
> +        <p class="hello">"Hello! Sharing world"</p>
- [ ]  For semantic purposes, this should be a `hx` not a `p` tag. This follows best practice for proper use of Html tags in your code

2023-05-24 03:05 UTC, Shedrack-Sunday commented on about.html
> +        <h2 class="creative">KAL TECH THINK UNLIMITED 2023</h2>
- [ ] Including at least one `h1` tag in an HTML file is crucial for semantic structure, accessibility, and SEO. It helps establish the main heading of a page, contributes to the document outline, and allows for consistent styling and visual hierarchy. Following this practice aligns with web development best practices and improves the overall user experience.

2023-05-24 03:05 UTC, Shedrack-Sunday commented on index.html
> +        <h4>CSS</h4>
- [ ] For this ssection, kindly make adjustment to the spacing as follows:
- The first header section and the second black section
- IInbetween the `main` heeader eriting and the boxes
- Kindly change the color of the boxes to grey just as in the original design. Same thing should be done to mobile 👍 

## Original design:
![image](https://github.com/Kal2403/capstone-project/assets/50990925/d763219b-a8f1-4a9a-b527-2da1b559f8bf)

## Your work:
![image](https://github.com/Kal2403/capstone-project/assets/50990925/fcf4e9e0-1cdd-47ec-887e-fd3a0e05420c)

2023-05-24 13:07 UTC, KanzaTahreem approved these changes
# Approved 🥳
Great work nailing it on the first attempt. I would like to express our deep appreciation for the time and effort you dedicated to this project 💪

**_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great, perfect!
-  ✅ Great work using the right GitHub Flow 
-  ✅ Your README looks professional, well done!
-  ✅ Commits are descriptive, good work.
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 13:07 UTC, KanzaTahreem commented on README.md
> + - Design idea by Cindy Shin in Behance, the author of the original design
- [OPTIONAL] I think it would be better to provide the links to the respective pages so that a user can easily find them 😎 You can consider something like below 👇

  Design idea by [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-05-24 13:17 UTC, merged

2023-05-30 08:18 UTC, LionRouge1 reviewed
Hi @Kal2403, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.